#!/bin/bash

set -eu
#set -x

function prerm_init() {
  export APP_NAME=bianbu-smart-album
  export APP_DATA=/usr/share/applications
}

function prerm_remove() {
  # Note: "__pycache__" should be remove during prerm, not postrm! 
  find /usr/src/bianbu-smart-album-* -name __pycache__ | xargs rm -rf
}

function prerm_upgrade() {
  :
}

function prerm_main() {
  if [ $# -eq 0 ]; then
    return;
  fi

  prerm_init
  case $1 in
    remove )            shift; prerm_remove $@;;
    upgrade )           shift; prerm_upgrade $@;;
    failed-upgrade )    ;;
  esac
}

args="$@"
prerm_main $@
